version: '3.8'

services:
  oms-web-ui:
    image: oms-web-ui
    build: .
    container_name: 'oms-web-ui'
    restart: always
    env_file:
      - .env
    networks:
      hub:
        ipv4_address: 172.2.0.33


networks:
  hub:
    driver: bridge
    external: true
